[package]
name = "two3tree"
version = "0.1.0"
authors = ["tony.astolfi <tony.astolfi@tamr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intervallum = "1.3.0"
gcollections = "1.4.0"
itertools = "0.8.2"